### ISSUE TITLE
./install_deps.sh Fails on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by sogrady** [brianwarner/facade#19] opened 2017-07-19 15:06 UTC
Just attempted an install and got the following. Will try and hunt down the dependencies manually in the meantime: 

root@redmonk-labs:~/facade/utilities# ./install_deps.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.0-xml' instead of 'php-dom'
Package python-bcrypt is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-bcrypt' has no installation candidate
E: Unable to locate package python-xlsxwriter

**Comment by brianwarner** [comment] 2017-07-19 15:24
Hmm, strange. I've been running it on Mint 18.1, which is (I believe) a
16.04 base. Must be a mismatch in the repos.

My internet connection is currently fried due to a lightning strike, but
will hopefully be restored later today.  When it comes back I'll grab a
copy of 16.04 and see if I can suggest some alternative packages.


On Jul 19, 2017 11:06 AM, "sogrady" <notifications@github.com> wrote:

Just attempted an install and got the following. Will try and hunt down the
dependencies manually in the meantime:

root@redmonk-labs:~/facade/utilities# ./install_deps.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.0-xml' instead of 'php-dom'
Package python-bcrypt is not available, but is referred to by another
package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-bcrypt' has no installation candidate
E: Unable to locate package python-xlsxwriter

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brianwarner/facade/issues/19>, or mute the thread

**Comment by brianwarner** [comment] 2017-07-21 01:35
Hmm, I am unable to replicate this.  I just did a vanilla Desktop install of 16.04.02 LTS, and ./install-deps.sh worked fine. It's finding python-bcrypt and python-xlsxwriter.

Which variant are you on?  Perhaps there's a difference in our sources?

**Comment by sogrady** [comment] 2017-07-21 01:41
Huh, interesting. Just spun up a Droplet on Digital Ocean. Will look at it in the morning.

**Comment by brianwarner** [comment] 2017-07-21 01:45
Ok cool, I'd be interested to know how it goes. I've just been running it locally.

I will caution, the initial analysis of a repo can be super CPU intensive, so I run it on machines where I don't pay for time. :-) Granted that's a one-time thing, once a commit has been analyzed it won't be checked again.  But for something with an active commit history, it can take a while.

**Comment by brianwarner** [comment] 2018-02-27 18:07
Doing some ticket cleanup.  Unfortunately I haven't been able to reproduce this on Ubuntu, so I'll close it for now...

**Closed by brianwarner** 2018-02-27 18:07 UTC
